apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-app
  template:
    metadata:
      labels:
        app: rock-app
    spec:
      containers:
        - name: lab5
          image: ghcr.io/p3nc/lab-rock-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-registry