apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-app
  template:
    metadata:
      labels:
        app: rock-app
    spec:
      containers:
        - name: lab5
          image: ghcr.io/p3nc/lab-rock-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):3306/rock_db?useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "$(DB_USER)"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "$(DB_PASS)"
      imagePullSecrets:
        - name: ghcr-registry