apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rock-app
  template:
    metadata:
      labels:
        app: rock-app
    spec:
      containers:
        # --- Контейнер 1: Ваш додаток ---
        - name: lab5
          image: ghcr.io/p3nc/lab-rock-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # ЦЕЙ БЛОК ЗАВАНТАЖИТЬ SPRING_DATASOURCE_USERNAME/PASSWORD
          envFrom:
            - secretRef:
                name: db-secrets

        # --- Контейнер 2: Cloud SQL Proxy Sidecar ---
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--auto-iam-authn"
            - "--structured-logs"
            - "$(CLOUD_SQL_CONNECTION_NAME)"
          securityContext:
            runAsNonRoot: true
          # ЦЕЙ БЛОК ЗАВАНТАЖИТЬ CLOUD_SQL_CONNECTION_NAME
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CLOUD_SQL_CONNECTION_NAME
      imagePullSecrets:
        - name: ghcr-registry