name: Rock App CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn package -B -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn verify
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  package-docker:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/p3nc/lab-rock-app:${{ github.sha }}

  deploy-gke:
    runs-on: ubuntu-latest
    needs: package-docker
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_KEY }}'
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: 'rock-app-cluster'
          location: 'us-central1'
          project_id: 'upbeat-isotope-477110-i4'
      - run: |
          kubectl delete secret ghcr-registry || true
          kubectl create secret docker-registry ghcr-registry \
            --docker-server=https://ghcr.io \
            --docker-password=${{ secrets.GH_PAT }} \
            --docker-email=zlyvko.of@gmail.com \
            --docker-username=${{ secrets.GH_USER }}
      - run: |
          kubectl delete secret db-secrets || true
          kubectl create secret generic db-secrets \
            --from-literal=SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }} \
            --from-literal=SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASS }} \
            --from-literal=CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
      - run: |
          sed -i 's|image: .*|image: ghcr.io/p3nc/lab-rock-app:${{ github.sha }}|g' deployment.yml
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
